### ISSUE TITLE
Zavádějící předvyplnění v registračním formuláři aplikace

### ISSUE THREAD

**Issue by GenaBitu** [skaut/ws.skautis.cz#6]
V registračním formuláři je u adres (všech tří) předvyplněno `http://` Kdo si toho nevšimne, tak si může omylem registrovat aplikaci přes http, i když by třeba chtěl https.

Návrhy na řešení:
 - Předvyplnit `https://` (security by default)
 - nepředvyplnit nic.

**Comment by sinacek** [comment]
díky, opraveno https://github.com/skaut/ws.skautis.cz/commit/b0f62cccf0dc7bc6aabc049b60a893599408fbb7
